### PR TITLE
feat: omit objects with empty values

### LINKED ISSUE #23: allow setting empty path
When path is set to `undefiend` or `null` the following code is generated:

```
8E63D5C4EFE34B3BAE93815F /* Frameworks */ = {
			isa = PBXGroup;
			children = (
				18285FBD1A3D4F05A3F47AC4 /* GoogleInterchangeUtilities.framework */,
			);
			name = Frameworks;
			path = undefined;
			sourceTree = "<group>";
		};
```

Since it is possible to create groups without a path it would be nice to not set a path when the path is `undefined` or `null`. Furthermore a path that equals `undefined` or `null` makes the Group appear red in xcode. This would also be fixed by simply dropping the path

### PR DESCRIPTION
**Pull request by n1ru4l**
Fixes #23

This is the quickest fix I could find

### CODE REVIEW

**Comment by janpio** [comment]
Isn't this a bit broad, possibly also removing stuff that should not be removed but fail as the param really should be there or the value really should be set?

We will definitely need some tests around this to be confident enough that this is working as intended I would say :/

**Comment by n1ru4l** [comment]
@janpio IMHO it does not make sense to set a value to null/undefined. And if the perpetrator intended to so he could simply set the value to `"null"` instead of `null` (or `"undefined"` instead of `undefined`.

However I can see your concern about breaking some stuff.

Maybe we could ship this with a option e.g. (`dropNullAndUndefined`: `boolean`)?

**Comment by n1ru4l** [comment]
@janpio I added some tests and fixed the implementation, also you will now have to pass `dropUndefinedOrNull` to `writeSync`, otherwise `undefined` and `null` values will be handled how they are atm

**Comment by janpio** [comment]
Having tests is great - thanks for making the changes.  
I'll let someone with more JS experience review the actual code.

**Comment by brodybits** [comment]
I am not a super expert with Xcode projects, will review the best I can.

I would favor renaming the option to something more meaningful, such as "dropFrameworksWithEmptyPath".

Otherwise it looks good, thanks for contributing the test cases as well.

**Comment by n1ru4l** [comment]
@brodybits `dropFrameworksWithEmptyPath` would be misleading because it changes the writer to drop more than just paths a.k.a every value that is null or undefined.

**Comment by brodybits** [comment]
As I said I am not an Xcode expert so it would help if you could better explain the actual problem and proposed change in behavior.

I find "NullOrUndefined" to be a bit ugly for the exported API. Also "dropUndefinedOrNull" does not give me a clear idea of what it actually does.

**Comment by n1ru4l** [comment]
Maybe `dropUndefinedOrNullValues` would be better 😅.

The problem is explained here: https://github.com/apache/cordova-node-xcode/issues/23

My take on the solution is a broader approach, which not only works for the path "property".

In my opinion it makes sense to omit a key from "writing" that has `undefined` or `null` as a value instead of setting it to a stringified version of `undefined` or `null`. 

I do not think that anyone who is currently using this library intends to set any property value to `undefined` or `null`. Nevertheless if anyone wants to achieve it he could simply set the value to `String(undefined)"` or `String(null)` (which has currently the same effect, like a described in my earlier comment).

However because I like the idea of having no breaking changes in patch/feature versions, I introduced the functionality to omit properties whose value is `undefined` or `null`.

**Example:**

Input Object:
```
const group = {
  name: "Frameworks",
  path: undefined,
  someOtherKey: null,
  foo: String(undefined),
  bar: String(null)
}
```

Result without option disabled:
```
8E63D5C4EFE34B3BAE93815F /* Frameworks */ = {
			name = Frameworks;
			path = undefined;
			someOtherKey = null;
			foo = undefined; 
			bar = null; 
		};
```

Result with option enabled:
```
8E63D5C4EFE34B3BAE93815F /* Frameworks */ = {
			name = Frameworks;
			foo = undefined; 
			bar = null;
		};
```

If you come up with a better name I will rename the option.

Here are some of my suggestions:

- `dropUndefinedOrNull`
- `dropUndefinedOrNullValues`
- `omitEmptyValues`

**Comment by hayouni** [comment]
for the file cordova-node-xcode/lib/pbxProject.js
in the function pbxProject.prototype.addBuildPhase:
we miss 2 parameter in the buildPhase object:
     buildPhase = {
            isa: buildPhaseType,
            buildActionMask: 2147483647,
            files: [],
            **inputFileListPaths: [],
            outputFileListPaths: [],**
            runOnlyForDeploymentPostprocessing: 0
        }

**Pull request merged**
