### PR TITLE
Update pbxProject.js

### PR DESCRIPTION
**Pull request by ZhengShouDong**
add function <updateProductBundleIdentifier>

### CODE REVIEW

**Comment by ZhengShouDong** [comment]
ok,has been added test

**Comment by shazron** [comment]
I ran the tests however, and your test failed.

**Comment by n1ru4l** [comment]
Is this feature really necessary since it is just an alias?

**Comment by brodybits** [comment]
Closing due to lack of response and lack of perceived need. @ZhengShouDong if you still need this change please respond to the requests by @shazron and @n1ru4l.

**Pull request closed without merging**
