### PR TITLE
WIP updates for discussion

### PR DESCRIPTION
**Pull request by brodybits**
(not all tested)

- update nodeunit from github:brodybits/nodeunit#tap-12 (as proposed in caolan/nodeunit/pull/356) to resolve [dev] audit issues (NOT an issue with "production" use)
- move pegjs to devDependencies, add npm pegjs script to make it easier to run, and update directions in README.md
- mark new major release with possible changes:
  - drop support for node pre-6.0
  - commit package-lock.json
  - remove simple-plist dependency & comment out pbxProject.prototype.addDataModelDocument which does not seem to be used by downstream cordova-ios, cordova-osx, or react-native consumers
- other minor updates

### CODE REVIEW

**Comment by dave-irvine** [comment]
@brodybits Sorry if this is a strange place to raise this, but is there a reason Issues are turned off for this repo? I'm having trouble with some of the functionality and need to check if I'm being stupid or if its a bug.

**Comment by brodybits** [comment]
@dave-irvine issues are active now. Cordova was using Apache JIRA for issues in the past.

**Comment by n1ru4l** [comment]
@brodybits Why is this repository is prefixed with cordova? It seems more generic and not cordova specific, also the npm package name is xcode.

**Comment by brodybits** [comment]
> It seems more generic and not cordova specific, also the npm package name is xcode.

Agreed on my part. The code was originally authored by someone in <https://github.com/alunny/node-xcode> then donated to the Apache Cordova project for maintenance.

I think the ultimate solution would be to move this project into a separate organization such as "xcode-tools" (taken but we can find another one) where we can add maintainers who are not necessarily part of Cordova, in a similar fashion to some iOS tools we maintain in <https://github.com/ios-control>.

We should probably raise this kind of a discussion in <dev@cordova.apache.org>.

**Comment by brodybits** [comment]
Closing this proposal now. Most of the items remaining are now listed in #20 for a major update. I just raised #27 to track the idea of removing `addDataModelDocument` and the related `simple-plist` dependency.

**Pull request closed without merging**
